

[package]
name = "Rules_10"
version = "1.0.0"
authors = []
upgrade_policy = "immutable"

[addresses]
ride = "_"

[dev-addresses]


[dependencies.AptosFramework]
local = "/Metro/aptos-core/aptos-move/framework/aptos-framework" 

[dependencies.AptosStdlib]
local = "/Metro/aptos-core/aptos-move/framework/aptos-stdlib" 




