







[package]
name = "Rondoval_Tivaevae"
version = "1.0.0"
authors = []

[addresses]
ride = "_"

[dev-addresses]



[dependencies.AptosStdlib]
local = "/Metro/aptos-core/aptos-move/framework/aptos-stdlib" 

[dependencies.AptosFramework]
local = "/Metro/aptos-core/aptos-move/framework/aptos-framework" 

[dependencies.Visiwa]
local = "/Metro/Mottos/Visiwa" 

[dependencies.Rondoval]
local = "/Metro/Mottos/Rondovals/Rondoval" 

[dependencies.Rondoval_Thermoplastic]
local = "/Metro/Mottos/Rondovals/Rondoval_Thermoplastic" 

[dependencies.Rondoval_Geimfara]
local = "/Metro/Mottos/Rondovals/Rondoval_Geimfara" 