

[package]
name = "Wonder_Types_01"
version = "1.0.0"
authors = []
upgrade_policy = "immutable"

[addresses]
Ride_01 = "_"

[dev-addresses]


[dependencies.AptosFramework]
local = "/Metro/aptos-core/aptos-move/framework/aptos-framework" 

[dependencies.AptosStdlib]
local = "/Metro/aptos-core/aptos-move/framework/aptos-stdlib" 




