



[package]
name = "Vote_Pack"
version = "1.0.0"
authors = []
upgrade_policy = "compatible"

[addresses]
Builder_01 = "_"

[dev-addresses]


[dependencies.AptosFramework]
local = "/Metro/aptos-core/aptos-move/framework/aptos-framework" 

[dependencies.AptosStdlib]
local = "/Metro/aptos-core/aptos-move/framework/aptos-stdlib" 

[dependencies.Rules_09]
local = "/Metro/Board/Rides_Published_Mainnet/Rules" 

[dependencies.Rules_10]
local = "/Metro/Board/Rides_Published_Mainnet/Rules_10" 
