

[package]
name = "Lava"
version = "1.0.0"
authors = []

[addresses]
ride = "_"

[dev-addresses]


[dependencies.AptosStdlib]
local = "/Metro/aptos-core/aptos-move/framework/aptos-stdlib" 

[dependencies.AptosFramework]
local = "/Metro/aptos-core/aptos-move/framework/aptos-framework" 

[dependencies.AptosTokenObjects]
local = "/Metro/aptos-core/aptos-move/framework/aptos-token-objects"

[dependencies.AptosToken]
local = "/Metro/aptos-core/aptos-move/framework/aptos-token"

[dependencies.Quarry]
local = "/Metro/Mottos/Quarry" 

[dependencies.Visiwa]
local = "/Metro/Mottos/Visiwa" 






