

[package]
name = "Allowed_Wallets_01"
version = "1.0.0"
authors = []
upgrade_policy = "immutable"

[addresses]
Ride_01 = "_"

[dev-addresses]

[dependencies.AptosStdlib]
local = "/Metro/aptos-core/aptos-move/framework/aptos-stdlib" 

[dependencies.AptosFramework]
local = "/Metro/aptos-core/aptos-move/framework/aptos-framework" 

[dependencies.Rules_10]
local = "/Metro/Board/Rides_Published_Mainnet/Rules_10" 


